In [129]:
import numpy as np

In [130]:
with open("input.txt") as file:
    lines=file.readlines()
    
lines=[line.strip() for line in lines]
len(lines)

99

In [131]:
len(lines[-1])

99

In [132]:
array=np.zeros((len(lines),len(lines[0])),int)
visible=array.copy()
scenic_scores=array.copy()

In [133]:
for i, line in enumerate(lines):
    for j, char in enumerate(line):
        array[i,j]=int(char)

array

array([[2, 2, 2, ..., 2, 1, 0],
       [1, 0, 2, ..., 1, 1, 1],
       [1, 0, 2, ..., 0, 2, 2],
       ...,
       [2, 0, 1, ..., 1, 1, 1],
       [2, 0, 2, ..., 0, 2, 2],
       [2, 1, 0, ..., 0, 1, 1]])

In [134]:
# Set all edges to be visible
visible[0,:]=visible[-1,:]=visible[:,0]=visible[:,-1]=1
visible

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [135]:
for i in range(1,array.shape[0]-1):
    for j in range(1,array.shape[1]-1):
        item=array[i,j]
        if item > max(array[i,:j]) or item > max(array[i,j+1:])\
            or item > max(array[i+1:,j]) or item > max(array[:i:,j]):
            visible[i,j]=1

visible


array([[1, 1, 1, ..., 1, 1, 1],
       [1, 0, 1, ..., 0, 0, 1],
       [1, 0, 1, ..., 0, 1, 1],
       ...,
       [1, 0, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [136]:
visible.sum()

1798

# Part 2

In [137]:
for i in range(1,array.shape[0]-1):
    for j in range(1,array.shape[1]-1):
        tree_length=array[i,j]
        viewing_distances=np.zeros((4),int)

        vert_dist=array.shape[0]-1
        hor_dist=array.shape[1]-1

        i_dist=i
        j_dist=j

        while(True): # Up
            i_dist+=1
            if array[i_dist,j_dist]>=tree_length or i_dist==vert_dist:
                break
        viewing_distances[0]=abs(i_dist-i)

        i_dist=i

        while(True): # Down
            i_dist-=1
            if array[i_dist,j_dist]>=tree_length or i_dist==0:
                break
        viewing_distances[1]=abs(i_dist-i)

        i_dist=i
        j_dist=j

        while(True): # Right
            j_dist+=1
            if array[i_dist,j_dist]>=tree_length or j_dist==vert_dist:
                break
        viewing_distances[2]=abs(j_dist-j)

        j_dist=j

        while(True): # Left
            j_dist-=1
            if array[i_dist,j_dist]>=tree_length or j_dist==0:
                break
        viewing_distances[3]=abs(j_dist-j)

        scenic_scores[i,j]=viewing_distances.prod()


In [138]:
scenic_scores

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  1,  6, ...,  2,  1,  0],
       [ 0,  1,  8, ...,  1, 16,  0],
       ...,
       [ 0,  1,  2, ..., 16,  2,  0],
       [ 0,  1, 32, ...,  1,  9,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [141]:
scenic_scores.max()

259308